### ISSUE TITLE
How do I use GLGExplainer to explain node classification tasks?

### ISSUE THREAD

**Issue by huduo0713** [steveazzolin/gnn_logic_global_expl#3]
Hello,

I think the method you proposed is very meaningful. And, I am trying to explain other node classification graph datasets using GLGExplainer. But I can't find where to replace the dataset. I would like to know how to change the dataset of your model.

I would be grateful if you could help.

**Comment by steveazzolin** [comment]
Thanks for your interest in our work.

You first have to train a separate GNN and use an off-the-shelf local explainer, like GNNExplainer or PGExplainer, to extract and save local explanations on disk. Then you have to also write a custom function to read those local explanations. You can find an example in `code/local_explanations.py/read_bamultishapes`.

If you take as an example the code provided in `BAMultiShapes.ipynb`, then you simply have to replace `DATASET_NAME ` with your actual name, and refer to the previously defined function to read local explanations from disk instead of calling my `read_bamultishapes`.

Hope this helps.
Steve

**Comment by huduo0713** [comment]
Hi Steve,
​Thank you so much for your detailed explanation and guidance!    I really appreciate your help.
​I’ll follow your instructions to explain  node classification datasets.
​Thanks again for your support!
​Best regards.
Duo
